# Generated by Django 3.0.5 on 2020-05-30 00:47

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseType',
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='author',
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default=main.models.gen_rand_str, max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=main.models.gen_rand_name),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
