# Generated by Django 3.0.5 on 2020-05-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='author',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
