# Generated by Django 2.2.9 on 2020-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_case_casetype_profile_rule_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_curator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
