# Generated by Django 2.2.9 on 2020-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200125_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='Not set', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Not set', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='Not set', max_length=100),
            preserve_default=False,
        ),
    ]
