# Generated by Django 3.0.5 on 2020-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200530_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='isFinished',
            field=models.BooleanField(default=True),
        ),
    ]
