# Generated by Django 3.0.5 on 2020-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_originalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
