# Generated by Django 2.2.9 on 2020-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rule_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rules',
            field=models.ManyToManyField(to='main.Rule'),
        ),
    ]
