# Generated by Django 2.2.9 on 2020-02-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_case_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
    ]
