# Generated by Django 3.0.5 on 2020-05-31 17:52

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uid',
            field=models.CharField(default=main.models.gen_rand_str, max_length=16),
        ),
    ]
