# Generated by Django 3.0.5 on 2020-06-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_document_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='string',
            name='case',
        ),
        migrations.AddField(
            model_name='string',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Document'),
        ),
    ]
